apiVersion: v1
kind: ConfigMap
metadata:
  name: bifrost-prod-env-config
  namespace: bifrost-prod
data:
  ENV: "prod"
  BASE_URL: "https://bifrost.ethanswan.com"
  OIDC_ISSUER_EXTERNAL: "https://identity.ethanswan.com"
  OIDC_ISSUER_INTERNAL: "http://identity.identity-prod.svc.cluster.local"
