apiVersion: v1
kind: ConfigMap
metadata:
  name: bifrost-prod-env-config
  namespace: bifrost-prod
data:
  ENV: "prod"
  BASE_URL: "https://bifrost.ethanswan.com"
  OIDC_ISSUER_EXTERNAL: "https://identity.ethanswan.com"
  OIDC_ISSUER_INTERNAL: "http://identity.identity-prod.svc.cluster.local"
  PREVIEW_SERVICES: "footstrike-api,footstrike-dashboard,identity"
  NEON_PROJECTS: "footstrike-api=aged-river-81935268/neondb/neondb_owner,identity=plain-heart-27630935/neondb/app"
  PREVIEW_OAUTH_CLIENT_ID: "oUYmMxjJaeyvnx_gVBddWYAkC88nhy6xxminHqTxRDc="
