apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bifrost-prod-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/ethans-services/secrets/bifrost_prod_oidc_client_id/versions/latest"
        path: "oidc_client_id"
      - resourceName: "projects/ethans-services/secrets/bifrost_prod_oidc_client_secret/versions/latest"
        path: "oidc_client_secret"
      - resourceName: "projects/ethans-services/secrets/bifrost_prod_session_secret/versions/latest"
        path: "session_secret"
  secretObjects:
    - secretName: bifrost-prod-secrets
      type: Opaque
      data:
        - objectName: oidc_client_id
          key: OIDC_CLIENT_ID
        - objectName: oidc_client_secret
          key: OIDC_CLIENT_SECRET
        - objectName: session_secret
          key: SESSION_SECRET
