apiVersion: v1
kind: ServiceAccount
metadata:
  name: bifrost-prod-ksa
  namespace: bifrost-prod
  annotations:
    iam.gke.io/gcp-service-account: bifrost-prod-sa@ethans-services.iam.gserviceaccount.com
