apiVersion: v1
kind: ServiceAccount
metadata:
  name: bifrost-staging-ksa
  namespace: bifrost-staging
  annotations:
    iam.gke.io/gcp-service-account: bifrost-staging-sa@ethans-services.iam.gserviceaccount.com
